# _____   ____ _______ _____ ____  _   _ ____________
# |  __ \ / __ \__   __|_   _/ __ \| \ | |___  /___  /
# | |__) | |  | | | |    | || |  | |  \| |  / /   / /
# |  ___/| |  | | | |    | || |  | | . ` | / /   / /
# | |    | |__| | | |   _| || |__| | |\  |/ /__ / /__
# |_|     \____/  |_|  |_____\____/|_| \_/_____/_____|

# Связаться с разработчиком: @zzrtk {TG}

# Подсказки:
# Формат: ЭФФЕКТ:УРОВЕНЬ:ДЛИТЕЛЬНОСТЬ_В_СЕКУНДАХ
# Пример: SPEED:1:15 = Скорость II на 15 секунд
# Уровень 0 = I, 1 = II и т.д.

# Эффекты зелий по версиям Minecraft:
# 🔹 Версии 1.8+
# - "SPEED:1:10"              # Скорость II
# - "SLOW:0:10"               # Замедление I
# - "FAST_DIGGING:0:10"       # Спешка (Haste)
# - "SLOW_DIGGING:0:10"       # Утомление (Fatigue)
# - "INCREASE_DAMAGE:1:10"    # Сила II
# - "HEAL:0:1"                # Мгновенное лечение I
# - "HARM:0:1"                # Моментальный урон I
# - "JUMP:1:10"               # Прыгучесть II
# - "NAUSEA:0:5"              # Тошнота
# - "REGENERATION:1:10"       # Регенерация II
# - "DAMAGE_RESISTANCE:0:10"  # Сопротивление урону
# - "FIRE_RESISTANCE:0:10"    # Огнестойкость
# - "WATER_BREATHING:0:10"    # Подводное дыхание
# - "INVISIBILITY:0:10"       # Невидимость
# - "BLINDNESS:0:5"           # Слепота
# - "NIGHT_VISION:0:10"       # Ночное зрение
# - "HUNGER:0:10"             # Голод
# - "WEAKNESS:0:10"           # Слабость
# - "POISON:0:10"             # Отравление
# - "WITHER:0:10"             # Иссушение
# - "HEALTH_BOOST:0:10"       # Доп. здоровье
# - "ABSORPTION:0:10"         # Поглощение
# - "SATURATION:0:1"          # Сытость (мгновенная)

# 🔹 Версии 1.9 — 1.13
# - "GLOWING:0:10"            # Свечение
# - "LEVITATION:0:5"          # Левитация
# - "LUCK:0:10"               # Удача
# - "UNLUCK:0:10"             # Неудача

# 🔹 Версии 1.13 — 1.14+
# - "SLOW_FALLING:0:10"       # Плавное падение
# - "CONDUIT_POWER:0:10"      # Сила источника
# - "DOLPHINS_GRACE:0:10"     # Ловкость дельфина

# 🔹 Версии 1.14 — 1.16+
# - "BAD_OMEN:0:60"           # Дурное знамение
# - "HERO_OF_THE_VILLAGE:0:60" # Герой деревни

# 🔹 Версия 1.19+
# - "DARKNESS:0:10"           # Темнота


potions:
  leto:
    name: "&e&lОТВАР ЛЕТО"
    lore:
      - ""
      - "&e▸ &fСопротивление I &7(&e1:00&7)"
      - "&e▸ &fРегенерация I &7(&e1:00&7)"
      - ""
    color: "253,245,0"
    hideAttributes: true
    splash_potion: false # питьевое зелье
    effects:
      - "DAMAGE_RESISTANCE:0:60" # 1 лвл : на 1 минуту
      - "REGENERATION:0:60" # 0:60 - 1 лвл : на 1 минуту
  vedma:
    name: "&8&lОТВАР ВЕДЬМЫ"
    lore:
      - ""
      - "&8▸ &fЗамедление III &7(&81:00&7)"
      - "&8▸ &fСлепота I &f&7(&80:15&7)"
      - ""
    color: "105,105,105"
    hideAttributes: true
    splash_potion: true # взрывчатое зелье
    effects:
      - "SLOW:2:60" # 3 лвл : на 1 минуту
      - "BLINDNESS:0:15" # 1 лвл : на 15 секунд
messages:
  no_permission: "&6&l(ЗЕЛЬЯ) &fУ вас нет &6прав&f для использования этой &6команды.."
  usage: "&6&l(ЗЕЛЬЯ) &fИспользование: &6/zpotion give <игрок> <зелье>"
  unknown_command: "&6&l(ЗЕЛЬЯ) &fНеизвестная &6команда."
  player_not_found: "&6&l(ЗЕЛЬЯ) &fИгрок не &6найден."
  potion_not_found: "&6&l(ЗЕЛЬЯ) &fЗелье не &6найдено."
  potion_received: "&6&l(ЗЕЛЬЯ) &fВы &6получили&f %potion%."
